version: '3.9'

services:

  db:
    container_name: db
    restart: always
    build:
      context: ./db
      dockerfile: dev.Dockerfile
    # Set environment variables directly in the docker-compose file
    # Set envrionment variables based on the .env file
    env_file:
      - .env-db.dev
    volumes:
      - volume_db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    tty: true
    ports:
      - 3306:3306
    networks:
      - gms_br0

  next-app:
    container_name: next-app
    restart: always
    build:
      context: ./next-app
      dockerfile: dev.Dockerfile
    # Set envrionment variables based on the .env file
    env_file:
      - .env-next-app.dev
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
    ports:
      - 3000:3000
    networks:
      - gms_br0

networks:
  gms_br0:
    external: true

volumes:
  volume_db: